### ISSUE TITLE
Buy Consult

### ISSUE THREAD

**Issue by jiangkaiqiang2024** [vogellacompany/support#6]
How do I buy in China？

**Comment by jnerlich** [comment]
Hello,
are you looking for consulting support, or do you want to buy a training at learn.vogella.com?
Best regards, Jennifer

**Comment by jiangkaiqiang2024** [comment]
Yes

**Comment by jiangkaiqiang2024** [comment]
I have already sent the email，But there are still some issues with account registration and purchase

**Comment by jnerlich** [comment]
Please find attached a step by step description on how to purchase a training.
[LP_HowToPurchase.pdf](https://github.com/user-attachments/files/17362594/LP_HowToPurchase.pdf)
