### ISSUE TITLE
Cannot generate p2 repository

### ISSUE THREAD

**Issue by SPCSM** [vogellacompany/support#9]
**Describe the issue**
I'm using Eclipse version 2023-03(4.27.0).  I selected "Eclipse Product Export Wizard" from my product file, and selected "Generate p2 repository," but the export fails with "/usr/local/eclipse/plugins/org.eclipse.pde.build_3.11.400.v20220923-1253/scripts/genericTargets.xml:240: A problem occurred while invoking the director."
I edited genericTargets.xml to add <record name="/tmp/eclipse-build.log" loglevel="verbose"></record>.  The log file contains:
Missing requirement: App xxx requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=17))' but it could not be found

**Provide URL**
N/A

**To Reproduce**
I cannot provide the Eclipse plugins that I'm using, but I
1. Go to the product file
2. Click on Eclipse Product Export Wizard
3. Un check 'Export source'
4. Check 'Generate p2 repository'
5. Check 'Allow for binary cycles in target platform'
6. Click on Finish
7. See error

**Expected behavior**
Generate p2 repository works

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Red Hat
 - Browser: N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I can run the app from the product file in Eclipse with no errors.  I can export the product and run it if I don't check 'Generate p2 repository."

**Comment by vogella** [comment]
The manual export wizard to not work reliable anymore, we typically recommend using a Tycho build for this. You can learn about using Tycho in our commercial training here https://learn.vogella.com/exercises/rich-client-platform/exercise-building-eclipse-rcp-applications-with-maven-3chf8#exercise-using-a-target-platform-for-the-build or in our free tutorials here https://www.vogella.com/tutorials/EclipseTycho/article.html#exercise-tycho-build-for-update-sites
